plugins {
    kotlin("jvm")
    id("viaduct-feature-app")
    id("me.champeau.jmh").version("0.7.3")
    `java-test-fixtures`
    id("kotlin-static-analysis")
}

dependencies {
    jmh(libs.jmh.annotation.processor)
    jmh(libs.jmh.core)

    api(libs.slf4j.api)

    implementation(project(":engine:engine-api"))
    implementation(project(":service:service-api"))
    implementation(project(":shared:dataloader"))
    implementation(project(":shared:deferred"))
    implementation(project(":shared:graphql"))
    implementation(project(":shared:logging"))
    implementation(project(":shared:utils"))
    implementation(project(":snipped:errors"))
    implementation(project(":tenant:tenant-api"))
    implementation(libs.caffeine)
    implementation(libs.graphql.java)
    implementation(libs.graphql.java.extension)
    implementation(libs.guice)
    implementation(libs.jackson.databind)
    implementation(libs.javax.inject)
    implementation(libs.jmh.core)
    implementation(libs.kotlinx.coroutines.core.jvm)
    implementation(libs.kotlinx.coroutines.jdk8)

    testFixturesImplementation(libs.caffeine)
    testFixturesImplementation(libs.graphql.java)
    testFixturesImplementation(libs.graphql.java.extension)
    testFixturesImplementation(libs.io.mockk.jvm)
    testFixturesImplementation(libs.kotest.property.jvm)
    testFixturesImplementation(libs.kotlinx.coroutines.core.jvm)
    testFixturesImplementation(libs.kotlinx.coroutines.jdk8)
    testFixturesImplementation(project(":engine:engine-api"))
    testFixturesImplementation(project(":engine:engine-runtime"))
    testFixturesImplementation(project(":service:service-api"))
    testFixturesImplementation(project(":shared:arbitrary"))
    testFixturesImplementation(testFixtures(project(":service:service-api")))

    jmhAnnotationProcessor(libs.jmh.annotation.processor)

    // JMH dependencies to access main and test sources
    jmhImplementation(project(":shared:arbitrary"))
    jmhImplementation(libs.kotlinx.coroutines.core.jvm)
    jmhImplementation(libs.kotlinx.coroutines.jdk8)
    jmhImplementation(libs.graphql.java)
    jmhImplementation(project(":engine:engine-runtime"))
    jmhImplementation(testFixtures(project(":engine:engine-runtime")))

    testImplementation(testFixtures(project(":engine:engine-api")))
    testImplementation(testFixtures(project(":engine:engine-runtime")))
    testImplementation(testFixtures(project(":service:service-api")))
    testImplementation(testFixtures(project(":shared:graphql")))
    testImplementation(project(":service:service-runtime"))
    testImplementation(project(":shared:arbitrary"))
    testImplementation(project(":shared:dataloader"))
    testImplementation(project(":snipped:errors"))
    testImplementation(libs.io.mockk.jvm)
    testImplementation(libs.kotest.property.jvm)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.strikt.core)
    testImplementation(libs.strikt.jvm)
}
