plugins {
    id("kotlin-project")
    id("viaduct-feature-app")
    id("me.champeau.jmh").version("0.7.3")
    `java-test-fixtures`
    id("kotlin-static-analysis")
}

dependencies {
    jmh(libs.jmh.annotation.processor)
    jmh(libs.jmh.core)

    api(libs.graphql.java)
    api(libs.jackson.annotations)
    api(libs.javax.inject)
    api(libs.kotlinx.coroutines.core.jvm)
    api(project(":engine:engine-api"))
    api(project(":service:service-api"))
    api(project(":shared:dataloader"))

    implementation(libs.caffeine)
    implementation(libs.checker.qual)
    implementation(libs.kotlinx.coroutines.jdk8)
    implementation(libs.slf4j.api)
    implementation(project(":shared:deferred"))
    implementation(project(":shared:graphql"))
    implementation(project(":shared:logging"))
    implementation(project(":shared:utils"))
    implementation(project(":snipped:errors"))
    implementation(project(":tenant:tenant-api"))

    testFixturesApi(libs.graphql.java)
    testFixturesApi(project(":engine:engine-api"))
    testFixturesApi(project(":service:service-api"))

    testFixturesImplementation(libs.caffeine)
    testFixturesImplementation(libs.graphql.java)
    testFixturesImplementation(libs.graphql.java.extension)
    testFixturesImplementation(libs.io.mockk.dsl)
    testFixturesImplementation(libs.io.mockk.jvm)
    testFixturesImplementation(libs.kotest.property.jvm)
    testFixturesImplementation(libs.kotlinx.coroutines.core.jvm)
    testFixturesImplementation(libs.kotlinx.coroutines.jdk8)
    testFixturesImplementation(project(":engine:engine-api"))
    testFixturesImplementation(project(":engine:engine-runtime"))
    testFixturesImplementation(project(":service:service-api"))
    testFixturesImplementation(project(":shared:arbitrary"))
    testFixturesImplementation(testFixtures(project(":service:service-api")))
    testFixturesImplementation(testFixtures(project(":service:service-api")))

    jmhAnnotationProcessor(libs.jmh.annotation.processor)

    // JMH dependencies to access main and test sources
    jmhImplementation(libs.graphql.java)
    jmhImplementation(libs.kotlinx.coroutines.core.jvm)
    jmhImplementation(libs.kotlinx.coroutines.jdk8)
    jmhImplementation(project(":engine:engine-runtime"))
    jmhImplementation(project(":shared:arbitrary"))
    jmhImplementation(testFixtures(project(":engine:engine-runtime")))

    testImplementation(libs.graphql.java.extension)
    testImplementation(libs.io.mockk.dsl)
    testImplementation(libs.io.mockk.jvm)
    testImplementation(libs.jackson.databind)
    testImplementation(libs.jmh.core)
    testImplementation(libs.jspecify)
    testImplementation(libs.kotest.property.jvm)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.strikt.core)
    testImplementation(project(":service:service-runtime"))
    testImplementation(project(":shared:arbitrary"))
    testImplementation(testFixtures(project(":engine:engine-api")))
    testImplementation(testFixtures(project(":engine:engine-runtime")))
    testImplementation(testFixtures(project(":service:service-api")))
    testImplementation(testFixtures(project(":shared:graphql")))
}
